### ISSUE TITLE
Determining correct sampling frequency?

### ISSUE THREAD

**Issue by hasanfarooq7** [fraunhoferportugal/tsfel#102]
Hi,

First thankyou for such a wonderful library and its real life saver. I wanted to clarify about sampling frequency so say that in my time series dataset, i have observation timestamped after every 10 minutes so should i set sampling frequency 'fs' to about 1/600 or 0.001667ish something?

**Comment by dmfolgado** [comment]
Hi! Thank you for your nice feedback. I'm glad our library is helping you. Yes, you're indeed correct. The `fs` parameter must receive the sampling frequency in Hz. Therefore, as you suggested you should pass `fs=1./600`. This parameter will ensure correct calculation for features relying on sampling frequency (e.g. most of the spectral features).
