### ISSUE TITLE
Understanding outputs: what's the difference between 0_Mean and 1_Mean?

### ISSUE THREAD

**Issue by patrickfleith** [fraunhoferportugal/tsfel#106]
Hi guys,
When running the following it extracts two sorts of statistical features. For example I get `0_Mean` but also `1_Mean`. It seems that the first is the regular mean but I cannot figure out from the documentation what is the later mean. Same question for all other features which are returned as 0_featureName and 1_featureName.

Could you clarify?

`import tsfel`
`cfg_file = tsfel.get_features_by_domain("statistical")`
`X_train = tsfel.time_series_features_extractor(cfg_file, dataset, fs=1, window_size=10)`

Best, Patrick

**Comment by dmfolgado** [comment]
Hi! Thank you! The 0, 1, 3, ... N refers to the number of the time series you have on your `dataset`. You probably have two columns in the `dataset` (that correspond to two time series).

Therefore, 0_Mean is the mean value with respect to the first column (first time series) and 1_Mean is the mean value with respect to the second column (second time series). If you use a pandas for your dataset and add column names, the 0, 1, ... N will be replaced by the columns names

This is still not properly documented. We will improve the documentation.

**Comment by patrickfleith** [comment]
Hi ! Oh yes sure indeed, this makes a lot of sense. Thanks for the quick answer. Please keep up with the good work. love tsfel so far !
