### ISSUE TITLE
Progress bar still show up with verbose = 0

### ISSUE THREAD

**Issue by patrickfleith** [fraunhoferportugal/tsfel#107]
Hi, unless I misunderstood how to fully disable progress bar, the `time_series_features_extractor()` stil displays a progress bar. It stays empty but still it prints something out which cause me troubles when trying to integrate tsfel with streamlit.

![image](https://user-images.githubusercontent.com/64135237/149310552-7278f5e3-5468-4c53-80ed-00f2446db8a4.png)

**Comment by dmfolgado** [comment]
Sorry for the delay. It seems it is indeed not working as expected. I'll try to replicate your issue. Can you please confirm if you're running on Windows, Linux or macOS?

**Comment by patrickfleith** [comment]
Sure: I am on macOS Big Sur 11.3.1

**Comment by dmfolgado** [comment]
And just to confirm you're running the latest version (0.1.4) of TSFEL?

**Comment by patrickfleith** [comment]
Yes confirmed 0.1.4

**Comment by dmfolgado** [comment]
I did some quick troubleshooting using Ubuntu 20.04.3 LTS.
It seems the unexpected behavior is only present when running TSFEL in the Jupyter Notebook. Can you test running TSFEL on the ipython console to check if it persists?
If it's the case we your have to investigate what is causing the unexpected behaviour in the Jupyter Notebook.

**Comment by patrickfleith** [comment]
I'll have a look on Thursday/Friday and come back to you

**Comment by patrickfleith** [comment]
Hi, I've run the same command from spyder 5.2.2 IPython Console. With verbose=1, the the progress bar appears as expected, with verbose=0, the progress does not appears, as expected. So no problem there.

**Comment by mmarcato** [comment]
I think this is what is causing my code not to run on Windows + Interactive Windows on VS code. I just ran my python script on the terminal and it worked, the progress bar wasn't shown.

**Comment by HanlinGao** [comment]
I met the same problem in the Jupyter notebook
