### ISSUE TITLE
Rolling Feature Generation 

### ISSUE THREAD

**Issue by Ashayp31** [fraunhoferportugal/tsfel#116]
Hello,

I would like to generate features for each observation of my time series over a given lookback. i.e for every entry in the time series over a fixed lookback period. I am slightly confused between the values fs and window size used in tsfel and whether this is possible. Would I need to set fs to 1 and window size to the lookback period I require? Would you know how to do this?
Thanks in advance

**Comment by mbarandas** [comment]
Hello @Ashayp31,
We apologize for the delay in responding.
If we have understood your query accurately, you intend to extract features using a predetermined window size. In this case, you should make use of the `window_size` parameter, which specifies the number of data points employed for feature extraction. Please note that the `fs` parameter is solely employed for computing certain features. As a subset of features' computation relies on the sampling frequency, it is not tied to window definition.
