### ISSUE TITLE
Issue in having features for each observation

### ISSUE THREAD

**Issue by aigarspetresevics** [fraunhoferportugal/tsfel#118]
I'd like to have a feature for each observation in my dataset, i.e row. This can be done by setting window_size = 1. But this is of no use since most of the features require a larger window size to be of any use. I therefore would like to implement a rolling window.

I believe it would be common sense to have this as default. Since often times you want your features to be in sync with your target variable and the whole of the dataset. 

Please can you demonstrate how this can be done? I noticed there was already a discussion about this but it was closed without a solution.

Thanks.

**Comment by dmfolgado** [comment]
Hi! I'm afraid I did not understand your query. The `window_size` parameter set up a rolling window of a given size and extracts features with your requested window size. Let me know if this is your question and if not please elaborate with an example so we can help you.
