### ISSUE TITLE
Last incomplete window

### ISSUE THREAD

**Issue by SheemsK** [fraunhoferportugal/tsfel#119]
Hi all,

Thanks for the brilliant package. I was just wondering about available possibilities regarding the last window if it is not complete. 

Imagine I have 52 data points and I want to split that in windows of size 10. Currently I get 5 windows and the last two data points are ignored. Is there a way to instead ignore the first two points? Is there any easy fix for this?

Thanks.

**Comment by dmfolgado** [comment]
Hi! Thanks for your kind feedback. 

We currently do not have such an option on `tsfel.time_series_features_extractor`nor `tsfel.signal_window_splitter`.
As a workaround, I suggest that you manually remove the first two points before passing the data to the main feature extractor method.
