### ISSUE TITLE
Request for Optional Batch ID Grouping Support

### ISSUE THREAD

**Issue by nadolsw** [fraunhoferportugal/tsfel#121]
First of all, great package - many thanks for your contributions!

One request is for the ability to specify a "batch" identifier column within a data frame and group by that column value as well as persisting those column values on the output feature matrix (similar to tsfresh which allows for an optional column_id parameter to be provided by the user).

As an example, after loading the UCIHAR dataset to a flattened/stacked dataframe:

**batchID   time   x_acc   y_acc   z_acc**
000001         1          X          Y           Z
000001         2          X          Y           Z
000001         3          X          Y           Z
...
000001        128      X          Y           Z          
000002         1         X          Y           Z    
...
000003         1         X          Y           Z   
...

Currently what is returned from the following is a dataframe without any reference to the input grouping:

```
import tsfel
cfg_file = tsfel.get_features_by_domain()
df_train_tsfel = df_train.set_index(['batchid', 'time'])
headers = df_train_tsfel.columns
tsfel_features = tsfel.time_series_features_extractor(cfg_file, df_train_tsfel, fs=50, window_size=250, header_names=headers)
```

Alternatively, could also just implicitly pass and utilize a pre-existing df index, if present. Apologies if this is already possible and I just missed it within the documentation. Ultimately the desired output would look like the following:

**batchID x_acc_feature1 x_acc_feature2 ... z_acc_featureN**
000001 ...
000002 ...
000003 ...
...

**Comment by dmfolgado** [comment]
Hi @nadolsw! We appreciate your kind words. As of today, we don't have such functionality. As a workaround, you might use the [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) where the input will be the batchID column. The feature extraction method uses [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) to split a signal into windows. You might use it as well to separate your batchIDs guaranteeing they are organized as your data before being passed to feature extraction. You probably need then to post-process the `signal_window_splitter` result to assign a unique batchID per row and ensure the same shape of the feature extraction output.

**Comment by b-y-f** [comment]
> Hi @nadolsw! We appreciate your kind words. As of today, we don't have such functionality. As a workaround, you might use the [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) where the input will be the batchID column. The feature extraction method uses [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) to split a signal into windows. You might use it as well to separate your batchIDs guaranteeing they are organized as your data before being passed to feature extraction. You probably need then to post-process the `signal_window_splitter` result to assign a unique batchID per row and ensure the same shape of the feature extraction output.

Hi, 

I have some time series like

```
SerialNo	ReadingDate	Import Wh Total	Export Wh Total
222222	2013-09-01 22:20:00	NaN	NaN
222222	2013-09-01 22:30:00	0.003	0.0
222222	2013-09-01 22:40:00	NaN	NaN
222222	2013-09-01 22:50:00	NaN	NaN
...
123213	2013-09-01 23:00:00	0.003	0.0
```

result I want:
```
id		f1	f2	fn
222222 		xx	xx	xx
123213		yy	yy	yy
```


How to split them, I want group and extract feature for them but when I use that `window_splitter`, it not worked as I want.

**Comment by b-y-f** [comment]
> > Hi @nadolsw! We appreciate your kind words. As of today, we don't have such functionality. As a workaround, you might use the [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) where the input will be the batchID column. The feature extraction method uses [`tsfel.utils.signal_window_splitter`](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L6) to split a signal into windows. You might use it as well to separate your batchIDs guaranteeing they are organized as your data before being passed to feature extraction. You probably need then to post-process the `signal_window_splitter` result to assign a unique batchID per row and ensure the same shape of the feature extraction output.
> 
> Hi,
> 
> I have some time series like
> 
> ```
> SerialNo	ReadingDate	Import Wh Total	Export Wh Total
> 222222	2013-09-01 22:20:00	NaN	NaN
> 222222	2013-09-01 22:30:00	0.003	0.0
> 222222	2013-09-01 22:40:00	NaN	NaN
> 222222	2013-09-01 22:50:00	NaN	NaN
> ...
> 123213	2013-09-01 23:00:00	0.003	0.0
> ```
> 
> result I want:
> 
> ```
> id		f1	f2	fn
> 222222 		xx	xx	xx
> 123213		yy	yy	yy
> ```
> 
> How to split them, I want group and extract feature for them but when I use that `window_splitter`, it did not work as I want.
> 
> <img alt="image" width="539" src="https://user-images.githubusercontent.com/13849223/191623200-c81f7af6-c0d5-44f4-a680-af870d4b8a51.png">

Does that means I need to group by pandas and extract feature one by one.?

**Comment by b-y-f** [comment]
Hi, @dmfolgado , Another question, if I manually split the data by each group, does the tool gives me the same features? like some group only get 100 rows and another get 100000 rows, are they come out the same number of rows, then I can merge them with a `for` loop after.
