### ISSUE TITLE
How to determine if the extracted features are correct

### ISSUE THREAD

**Issue by Akai-ai** [fraunhoferportugal/tsfel#122]
When I extract the MFCC and LPCC feature matrix, how can I tell that there is no problem with my extraction? Is it possible to reverse the reconstruction to calculate their relative errors?

**Comment by dmfolgado** [comment]
Hi! All the features we have implemented are unit tested.
You can convert MFCCs back to the waveform audio signal using the [`librosa.feature.inverse.mfcc_to_audio`](https://librosa.org/doc/main/generated/librosa.feature.inverse.mfcc_to_audio.html). As a naive approach to measuring the reconstruction error, I guess you can calculate the RMSE and/or MAE between the original and reconstructed waveforms.
