### ISSUE TITLE
What is the difference between fsfel and tsfresh?

### ISSUE THREAD

**Issue by b-y-f** [fraunhoferportugal/tsfel#124]

**Comment by b-y-f** [comment]
> This fact is relevant in scenarios where feature extraction is computed in embedded devices such as wearables, with limited computational resources. TSFEL is being used to support feature extraction on inertial data acquired by smartphones and wearables in the context of Human Activity Recognition (HAR)


Is it good for ts, smart meter data?

**Comment by dmfolgado** [comment]
Both libraries have the same purpose and similar functionalities. However, they might not contain the very identical set of implemented features. I do believe the most adequate would be to take the benefits from each and use them complementary.

**Comment by b-y-f** [comment]
I have some very long-duration data for each sensor, like 365*1000+ points for each sensor, that makes feature extraction extremely slow in fresh, does this one increase performance?

**Comment by dmfolgado** [comment]
There is some literature that might suggest that tsfel can be faster: https://arxiv.org/pdf/2110.10914.pdf.
I suggest that you test your use case.
