### ISSUE TITLE
Some questions for the module

### ISSUE THREAD

**Issue by b-y-f** [fraunhoferportugal/tsfel#126]
- The module will generate a different number of features depending on the length of the time series. But I got the different lengths of time series, how to make them all have the same number of the feature so I can merge them?
- Does it have some group by id feature? so I can merge all the ts data into one file and process them together?
- I saw in the example notebook, we can share a google link to `featext@featext.iam.gserviceaccount.com`  then we can extract features from that shared file name, but it gives an error.

**Comment by mbarandas** [comment]
Hi @b-y-f,
We apologize for the delay in responding.

* To achieve consistency in the number of features, you must manually configure the hyperparameters governing the quantity of output features in the JSON file. The discrepancy you're encountering could be linked to the `fft_mean_coeff` function. In case any of your time series has fewer than 512 data points, it's essential to modify the `nfreq` parameter within the `fft_mean_coeff` function accordingly.

* TSFEL does not currently offer a comparable feature for grouping by ID.

* Please note that the Google Sheets example has been deprecated and is no longer supported in the latest release.
