### ISSUE TITLE
Getting error "Input signal must have a length >= n_coeff"

### ISSUE THREAD

**Issue by deepkachhawa7** [fraunhoferportugal/tsfel#132]
Hello team , 

I am planning to use tsfel package for feature generation for my work and started giving it a try on a small sample. I am getting below error. 
"ValueError: Input signal must have a length >= n_coeff"
Sample code : 

import pandas as pd
  
data = [[3], [4], [6],[7],[6],[6]]
  
df = pd.DataFrame(data, columns=['AD'])

df

import tsfel
cfg = tsfel.get_features_by_domain()
X = tsfel.time_series_features_extractor(cfg, df,window_size=3)

I have tried with the example dataset and with that, it is working fine.

I would like to use tsfel to extract feature for this [dataset|https://www.kaggle.com/competitions/LANL-Earthquake-Prediction/data]
Idea is to use a window of 150000 samples for acoustic_data column and extract the features for them with tsfel. 

Can you please let me know what i am missing here ?

**Comment by mbarandas** [comment]
Hello @deepkachhawa7,
We apologize for the delay in responding.
As a default, `n_coeff` within the lpcc function is configured to 12. This implies that the function aims to extract 12 coefficients. Considering your input signal consists of only 6 data points, attempting to derive 12 coefficients becomes unfeasible. Consequently, you must either diminish the number of coefficients or augment the size of the input signal.
