### ISSUE TITLE
new numpy version uses astype(bool) instead of astype(np.bool)

### ISSUE THREAD

**Issue by HanneloreStr** [fraunhoferportugal/tsfel#133]
I am receiving an error with the following command:
corr_features = tsfel.correlated_features(X_train)

stating that for this line in the TSFEL library
86 upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Apparently, with the newer version of numpy, it should be just bool instead of np.bool. I tried to downgrade my numpy version, but then I receive an error that I cannot downgrade the numpy version to that level with my current version of python. Perhaps there is an easier way to solve this problem on the development side? Thank you in advance.

**Comment by mbarandas** [comment]
Hi @HanneloreStr,
Thank you for using TSFEL and for bringing attention to this issue.
We will be releasing a new version of tsfel with this update shortly.
