### ISSUE TITLE
index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ibilgen** [fraunhoferportugal/tsfel#134]
I think there is a bug here

I have list of signals of same shape --> 1800 x 2. Two signals per sample, which are of length 1800. 
Although all signals have same shape (and also similar patterns) tsfel returns error for some signals!

For example, from san 0 it successfully extract 670 spectral features
`tsfel.time_series_features_extractor(cfg_spec, signals[0], fs=fs)`

However for signal 4 return below index error!
`tsfel.time_series_features_extractor(cfg_spec, signals[4], fs=fs)`

> IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by mbarandas** [comment]
Hi @ibilgen,
Could you please provide us with more details about the issue you're facing?
In order to assist you effectively, we require the complete error trace and the input signal that is triggering the error.

**Comment by ibilgen** [comment]
> Hi @ibilgen, Could you please provide us with more details about the issue you're facing? In order to assist you effectively, we require the complete error trace and the input signal that is triggering the error.

I have several signals of length 1800. The be more specific, I present two signals below.

![image](https://github.com/fraunhoferportugal/tsfel/assets/4732535/414533cc-c1bf-4f63-ab23-d9e8181c04e7)

the signals are in format float64 as follows  

```
00:00:00,0.0
00:00:01,0.0
00:00:02,0.0
00:00:03,74.0
00:00:04,148.0
00:00:05,149.0
...
```

```
> signals[0].shape, signals[1].shape
((1800, 1), (1800, 1))
```


```

signals[0] is completed successfully:

```
> cfg_spec = tsfel.get_features_by_domain("spectral")
> s0_feat = tsfel.time_series_features_extractor(cfg_spec, signals[0], fs=1)

*** Feature extraction started ***
26
*** Feature extraction finished ***
```

But signals[1] returns an error as given below:

```
> s1_feat = tsfel.time_series_features_extractor(cfg_spec, signals[1], fs=1)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[42], line 1
----> 1 s1_feat = tsfel.time_series_features_extractor(cfg_spec, signals[1], fs=1)

File ~\anaconda3\envs\storaige\lib\site-packages\tsfel\feature_extraction\calc_features.py:268, in time_series_features_extractor(dict_features, signal_windows, fs, verbose, **kwargs)
    265 features_final = pd.DataFrame()
    267 if isinstance(signal_windows, pd.DataFrame):
--> 268     features_final = calc_window_features(dict_features, signal_windows, fs, verbose=verbose, single_window=True,
    269                                           features_path=features_path,
    270                                           header_names=names)
    271 else:
    272     if isinstance(signal_windows[0], numbers.Real):

File ~\anaconda3\envs\storaige\lib\site-packages\tsfel\feature_extraction\calc_features.py:466, in calc_window_features(dict_features, signal_window, fs, verbose, single_window, **kwargs)
    463     execf += ', ' + str(parameters_total).translate(str.maketrans({'[': '', ']': '', "'": ''}))
    465 execf += ')'
--> 466 eval_result = eval(execf, locals())
    468 # Function returns more than one element
    469 if type(eval_result) == tuple:

File <string>:1

File ~\anaconda3\envs\storaige\lib\site-packages\tsfel\feature_extraction\features.py:1454, in power_bandwidth(signal, fs)
   1452 # Computing the lower and upper limits of power bandwidth
   1453 cum_power = np.cumsum(power)
-> 1454 f_lower = freq[np.where(cum_power >= cum_power[-1] * 0.95)[0][0]]
   1456 cum_power_inv = np.cumsum(power[::-1])
   1457 f_upper = freq[np.abs(np.where(cum_power_inv >= cum_power[-1] * 0.95)[0][0] - len(power) + 1)]

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by mbarandas** [comment]
Hi @ibilgen,
Could you please confirm whether your signal[1] contains any NaN values? The occurrence of this error might indicate an issue with the power calculation, possibly linked to the signal itself. If there are no NaN values in your signal, can you share the data with me? This would help me replicate the error.

**Comment by ibilgen** [comment]
> Hi @ibilgen, Could you please confirm whether your signal[1] contains any NaN values? The occurrence of this error might indicate an issue with the power calculation, possibly linked to the signal itself. If there are no NaN values in your signal, can you share the data with me? This would help me replicate the error.

Oh yes, there are a few NaN values in sig2. It worked after dropping them. 

Thanks!
