### ISSUE TITLE
Absolute Energy and Autocorrelation with equal value

### ISSUE THREAD

**Issue by JoanaSofia** [fraunhoferportugal/tsfel#142]
Hi,
I noticed that both the absolute energy and the autocorrelation of the signals return the same value, which seems unusual. I believe they should differ. Could you please look into this?

Thank you in advance!

**Comment by dmfolgado** [comment]
I'm working on this improvement. The `autocorrelation` feature will now rely on the ACF from `statsmodels`.
I plan to extract the time constant (τ) defined as the autocorrelation falling to 1/e of its initial value. Some tests below:

![MicrosoftTeams-image](https://github.com/fraunhoferportugal/tsfel/assets/6944301/9546a4b0-c0ad-442a-8285-140fffb33861)

The second row is the ACF with the respective value of τ. In the third row, I annotated the $\alpha$ from DFA as other tests we're conducting in parallel to prepare the introduction of fractal features.

**Comment by dmfolgado** [comment]
This issue was fixed in v.0.1.7
