### ISSUE TITLE
Option to realign resulting dataframe's index to input

### ISSUE THREAD

**Issue by mgalas** [fraunhoferportugal/tsfel#143]
Working with features obtained from **time_series_features_extractor** function is very non-intuitive as **fs** and **window_size** parameters can significantly alter the shape of resulting dataframe. A common task that follows is then to realign the index of resulting dataframe to the index of input dataframe (example below). This can be easily handled as part of **time_series_features_extractor** function with an additional boolean realign parameter indicating if a user needs the result to be realigned with input index.

**example input_df**
'2023-01-01', value1
'2023-01-02', value2

**current result_df for fs=1, window_size = 2**
1, feature1

**proposed realigned_df for fs=1, window_size = 2**
'2023-01-01', N/A
'2023-01-02', feature1

**Comment by isabelcurioso** [comment]
Hi! Thank you for your interest in tsfel. We appreciate your suggestion for a future release. For now, you can use the following code to realign the output dataframe as per your request.

```
# Example values
data = pd.DataFrame(np.random.rand(4,3), columns=['Acc1', 'Acc2', 'Acc3'])
window_size = 2
overlap = 0
settings = get_features_by_domain('temporal')
 
windows = signal_window_splitter(data, window_size, overlap)
last_indexes = [df.iloc[-1].name for df in windows]
features = time_series_features_extractor(settings, windows)
features.set_index(pd.Index(last_indexes), inplace=True)
final_df = pd.DataFrame(features, index=data.index)
 
# data is a pandas DataFrame with the time series data. Example:
#                 Acc1            Acc2            Acc3
# 0           0.538483       -0.930359       10.402390
# 1           0.875264       -0.839553       10.283643
# 2           0.202794       -1.076978       10.025708
# 3           0.455223       -1.151602       10.164102
# window_size and overlap are parameters of the signal_window_splitter function.
# settings is a dictionary with the features to extract (parameter dict_features of
# the time_series_Features_extractor function).
```

**Comment by mgalas** [comment]
Hi @isabelcurioso, thank you for the code snippet, it was very kind of you to provide it.
