### ISSUE TITLE
`fs` and `window_size`

### ISSUE THREAD

**Issue by YRC10** [fraunhoferportugal/tsfel#149]
Hello, I want to ensure I understand the definitions of `fs` and `window_size` correctly. If I'm wrong, please feel free to correct me.

If I understand right, `fs` is the sampling frequency of my time series data. For example, if the time series data is collected by a 100Hz sensor, then `fs` should be 100 in this case, right? 

`window_size` is the number of samples that we want to analyze at the same time. For example, if I want to analyze 100 time series data at a time (w_size=100 and w_offset=50 as shown in the figure below), then the value of `window_size` should be set to 100 and `overlap` should be set to 0.5, right?

I'd also like to know if there are default values for `fs` and `window_size`?

![image](https://github.com/fraunhoferportugal/tsfel/assets/80633253/e994b253-e26a-4dcb-b41e-8f1034df90e1)

And when I tried `TSFEL_HAR_Example.ipynb`, I found that increasing `window_size` would increase the number of feature types (number of columns generated), which made me confused. For example, when I set `window_size` to 100, the number of columns will soar to more than 20,000. From my understanding, the number of feature types is fixed, and `window_size` will only affect the number of features (number of rows generated). I would like to ask what is the cause of this?

**Comment by dmfolgado** [comment]
Hi! You correctly understand the concepts of `fs` and `window_size`, but you're applying the `window_size` concept in an improper use case. The example of the `TSFEL_HAR_Example.ipynb` already has the input data divided into multiple windows. By trying to divide into further windows the data with the input shape as it is, it will consider that the windows are different dimensions (axes), and thus, it will apply the feature set for all the dimensions (thus the high number of columns).

If you need to divide the data into windows, probably the `TSFEL_HAR_Example.ipynb` is not the most adequate example. Please let me know if you have any further questions on input data structure and output dimensions.

**Comment by dmfolgado** [comment]
Some legacy notebooks are in the repository but not updated according to the latest versions. We'll update those notebooks soon. In the meantime, you can use the `window_size` and `overlap` arguments as you described, and let us know if you need further help.

**Comment by YRC10** [comment]
Thank you, Duarte!
