### ISSUE TITLE
`FutureWarning: The histogram feature was deprecated...` when using `tsfel.time_series_features_extractor`

### ISSUE THREAD

**Issue by GniLudio** [fraunhoferportugal/tsfel#162]
I get the warning
```
tsfel\feature_extraction\features.py:498: FutureWarning: The histogram feature was deprecated in version 0.1.8 and will be replaced by the mode of histogram in 0.1.9. From then on, only a single feature value will be returned.
  warnings.warn(
```
when using `tsfel.time_series_features_extractor`.

### Note
* On Linux the warning appears every time (not only the first time) `tsfel.time_series_features_extractor` is used.
  * I don't know the exact reason/difference that causes the warning to be logged multiple times.
* I found [this](https://github.com/fraunhoferportugal/tsfel/issues/6) similar issue, but that's already closed and 5 years ago.

**Comment by dmfolgado** [comment]
Hi @GniLudio thank you for letting us know. The warning is related to the deprecation of the current histogram feature implementation. We will switch to a different implementation that does not require defining the limits of the histogram (the previous version did so, and if not properly adjusted, the histogram feature could not make much sense). 

We plan to release the revised histogram implementation soon and remove the warning. Out of curiosity, you mentioned that Linux appears every time. Have you also had that issue on Windows?

**Comment by dmfolgado** [comment]
Interesting. Thank you for letting me know.
