### ISSUE TITLE
Additional TSFEL examples

### ISSUE THREAD

**Issue by dmfolgado** [fraunhoferportugal/tsfel#19]
It would be nice to have additional examples of TSFEL apart from HAR.

**Comment by dmfolgado** [comment]
This enhancement is implemented in the upcoming version of TSFEL expected to be released soon.

**Comment by espjose** [comment]
Hola serian tan amables de explicarme el proceso para elegir solo las caracterisitcas que deseo en el texto mensionan que se debe "Puede cargar cualquiera de los diccionarios de configuración anteriores y establecer las funciones que no le interesan o editar un diccionario de forma manual o programática y establecer el como o según corresponda", sin embargo no entiendo muy bien el proceso.
