### ISSUE TITLE
Tsfel on google Colab

### ISSUE THREAD

**Issue by oattao** [fraunhoferportugal/tsfel#36]
Hi. Thanks for the amazing work.
I would like to use tsfel on Colab. 
Could you please tell me how to access the that colab file?

**Comment by smlsantos** [comment]
Hello @oattao!

First of all, thank you for your interest in using TSFEL. 

On Colab we have examples of how to use the library. You can find them [here](https://colab.research.google.com/github/fraunhoferportugal/tsfel/blob/development/notebooks/TSFEL_HAR_Example.ipynb) or by clicking on Open in Colab from TSFEL’s Github  <img width="611" alt="Screenshot 2020-05-15 at 11 06 49" src="https://user-images.githubusercontent.com/25684521/82048119-f0198600-96ab-11ea-9c54-77a184dec45d.png">
Please note that TSFEL’s latest version is yet to be released on master, thus we recommend using Colab from the development branch.

**Comment by jpalma-espinosa** [comment]
sorry for re-opening this.
I have just run it on a custom google colab code. It is as easy as
```python
%pip install tsfel #this will install the module and load it on your colab's instance
import numpy as np
import matplotlib.pyplot as plt
import tsfel
#rest of the code
```
Happy tsfeling =)
