### ISSUE TITLE
System Message: WARNING While opening List of features in docs.

### ISSUE THREAD

**Issue by Salmankhancodes** [fraunhoferportugal/tsfel#43]
While opening the [Feature list](https://tsfel.readthedocs.io/en/latest/descriptions/feature_list.html) from docs of tsfel , it's showing errors in place of code-area.

```
System Message: WARNING/2 (/home/docs/checkouts/readthedocs.org/user_builds/tsfel/checkouts/latest/docs/descriptions/feature_list.rst, line 6)
failed to import tsfel.feature_extraction.features
System Message: WARNING/2 (/home/docs/checkouts/readthedocs.org/user_builds/tsfel/checkouts/latest/docs/descriptions/feature_list.rst, line 6)

toctree references unknown document ‘descriptions/_generated/tsfel.feature_extraction.features’

```

![issuee](https://user-images.githubusercontent.com/57289757/84934563-1e4c1480-b0f5-11ea-89d7-876053c24017.png)

**Comment by dmfolgado** [comment]
Hi! Thanks for spotting the error. It is being prompted when we try to generate the documentation with readthedocs. We will fix that asap. In the meantime, you can have read the list of available features here: https://github.com/fraunhoferportugal/tsfel#available-features, although does not explicitly provide the names of each method.

**Comment by Salmankhancodes** [comment]
Thanks for the fix  👍
