### ISSUE TITLE
a problem with correlation_report

### ISSUE THREAD

**Issue by Ruhallah93** [fraunhoferportugal/tsfel#46]
Give a parameter instead of the question in input for removing highly correlated features at correlation_report.

**Comment by lmfernandes96** [comment]
Dear @Ruhallah93,

Thank you for your interest in TSFEL.

The **correlation_report** method no longer exists in the updated version of TSFEL, instead, we have the **correlated_features** method that returns the index of the correlated features according to a correlation threshold (input parameter).

During this week we are going to release a new version of TSFEL that includes this improvement.

If more issues arise, feel free to contact us.

**Comment by lmfernandes96** [comment]
Issue solved in **Release version 0.1.3**
