### ISSUE TITLE
<RuntimeWarning: invalid value encountered in sqrt>

### ISSUE THREAD

**Issue by Huii** [fraunhoferportugal/tsfel#54]
Thank you very much for this create library, first of all!

The following code in the "distance" function in features.py:
```
    diff_sig = np.diff(signal)
    return np.sum([np.sqrt(1 + diff_sig ** 2)])
```
should be changed to:
```
    diff_sig = np.diff(signal)
    diff_sigFloat = diff_sig.astype(float)
    return np.sum([np.sqrt(1 + diff_sigFloat ** 2)])
```

The reason for that is that otherwise an integer overflow might occur for larger numbers, which results in negative numbers, which, in turn, results in an "invalid value" error.

**Comment by lmfernandes96** [comment]
Hi Hui!

Thank you for your interest in TSFEL.

We have followed your suggestion and fixed the bug in the Pull Request #55.
Thank you for contributing to the library, if you find more problems feel free to contact us!
