### ISSUE TITLE
Extract relevant features from different domain.

### ISSUE THREAD

**Issue by sanbuddhacharyas** [fraunhoferportugal/tsfel#57]
It takes a long time to extract all domain features so, How can I extract only relevant features from all three domains? 
Please help!!!

**Comment by dmfolgado** [comment]
Can you elaborate on do you understand by "relevant features"? 
Usually, relevant features can be selected before feature extraction if you have some domain-knowledge on the most adequate features for your data. Alternatively, relevant features can also be selected after the feature extraction by applying feature selection methods.

**Comment by dmfolgado** [comment]
1. Download the[ features.json](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/feature_extraction/features.json) and select each feature you want to use by changing the `use` parameter (`yes` or `no` value).

2. Load the customized json using the `tsfel.load_json` method.
 
```python
import tsfel
import pandas as pd
 
# load dataset
df = pd.read_csv('Dataset.txt')
 
# Retrieves your pre-defined feature configuration file
cfg = tsfel.load_json(your_json_path)

# Extract features
X = tsfel.time_series_features_extractor(cfg, df)
```
