### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 12: character maps to <undefined>

### ISSUE THREAD

**Issue by Huii** [fraunhoferportugal/tsfel#60]
I'm using TSFEL on a Windows 10 machine and end up with the following error message whenever I enable the progress bar for feature extraction:

`UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 12: character maps to <undefined>`

I'm not really sure why this problem occurs but [this Stackoverflow thread](https://stackoverflow.com/questions/14630288/unicodeencodeerror-charmap-codec-cant-encode-character-maps-to-undefined) provides some suggestions on how to mitigate the issue.

If I set the verbose parameter to 0, everything works as expected.

**Comment by lmfernandes96** [comment]
Hello Hui,

Thank you for your interest in TSFEL.

I would kindly ask you the following information so that I can replicate this issue:
1) Which version of TSFEL are you using?
2) In which Python Interface are you enabling the progress bar?

**Comment by Huii** [comment]
Hello @lmfernandes96,

I'm using the current PyPi version taken from here: https://pypi.org/project/tsfel/. I'm enabling the progress bar via the following call:

`tsfel.time_series_features_extractor(configuration,testX,verbose=1)`

The Python version I'm using is 3.7.4.

**Comment by lmfernandes96** [comment]
Thank you for this information.

I am still not able to replicate this issue.
Could you please tell me where are you running your code? For instance: Pycharm, Jupyter Notebook, Anaconda console, ... ?
And if it is possible could you share your configuration file and testX?

**Comment by Huii** [comment]
I'm running the code via the Pydev plugin from within Eclipse. The configuration is simply given as follows to calculate all features:
`configuration = tsfel.get_features_by_domain()`

Unfortunately, I can't share the testX input array with you as the data is confidential. Is there any other information that could be useful to solve this issue?

**Comment by lmfernandes96** [comment]
Hi Huii,

I was able to replicate your issue with the information you provide me, thank you.
It seems that the issue that you are having is not related to tsfel but to the encoding that the console of Eclipse is using.
I did some tests and if you change the text file encoding to UTF-8 it will work. 
To do so, follow these steps: Window -> Preferences -> General -> Workspace : Text file encoding (Here change to UTF-8)

After you try this, please tell me if it works.

Thank you!

**Comment by Huii** [comment]
Thank you very much. That did the trick indeed. 👍
