### ISSUE TITLE
time series with variable length?

### ISSUE THREAD

**Issue by jesuslovesyiyi** [fraunhoferportugal/tsfel#62]
Hi, I am curious whether we could use this to extract features from multi-dimensional time series with variable lengths?

**Comment by dmfolgado** [comment]
Hi, yes it is possible indeed. That's actually one of the functionalities that weren't properly addressed by similar packages when we started the development of TSFEL. To do so I recommend that the time series are stored in a data file and processed using the dataset_features_extractor.

We are still updating the documentation of this functionality. In the meantime, you can read _Section 2.2.1. Data ingestion and preprocessing_ of [TSFEL publication](https://www.sciencedirect.com/science/article/pii/S2352711020300017) which addresses that topic.
