### ISSUE TITLE
Installation problem using Anaconda 

### ISSUE THREAD

**Issue by raedbsili1991** [fraunhoferportugal/tsfel#67]
Hello, 

I am using Anaconda, 
Do you have an idea on why I can't install the packages using pip ?  
![image](https://user-images.githubusercontent.com/31764213/95361751-6e7dfb00-08cd-11eb-94b3-1f79797a2fdd.png)

**Comment by dmfolgado** [comment]
Hello! Is your issue specific to TSFEL or are you experiencing the issue with other packages?

**Comment by raedbsili1991** [comment]
Hello, 

No this is specific to only TSFEL.  
Any suggestions ?

**Comment by dmfolgado** [comment]
We could not reproduce your issue from our side. I'll close for now the issue. Let us know if you have any more issues.
