### ISSUE TITLE
Working with unevenly sampled data 

### ISSUE THREAD

**Issue by senovr** [fraunhoferportugal/tsfel#72]
I have a question about the following usage scenario of tsfel:
I have a pandas data frame with the following structure:
```
time           value
2020-01-01       1.2
2020-01-02       1.3
2020-01-04       1.1
2020-01-07       1.0
2020-01-08       1.5
```

As you may see, the sampling frequency is not constant (sometimes it is once per day, sometimes it is once per few days).
Can you please let me know if tsfel can handle this kind of data to extract time-series features?

**Comment by dmfolgado** [comment]
Hi! TSFEL does not handle unevenly sampled data by default. Some of the features (e.g. spectral domain) require that you state the sampling frequency to compute the feature values correctly. Can you provide more insights on your use case requirements? What would be an adequate window duration for the feature extraction?

A workaround to analyze unevenly spaced time series is to transform the data into equally spaced observations using interpolation (e.g. linear interpolation). After that you could use TSFEL directly on this converted equally spaced data.
