### ISSUE TITLE
multiple timeseries feature extraction

### ISSUE THREAD

**Issue by IrenXu** [fraunhoferportugal/tsfel#74]
Hi,

I am using tsfel for 564 timeseries analysis, I want to extract the features of each time course and get a dataframe containing the features for all time courses (they should have the same column and each row represents a specific time course)

So I used a loop for this, my dataset has nan in some time course.

My code looks like this, but it only shows the feature extraction started, never finished and could not return the features.
![image](https://user-images.githubusercontent.com/77282283/105985186-0c6f1e80-6093-11eb-8cba-5fae7955cf06.png)
Any suggestions on this?

Many thanks!

**Comment by mbarandas** [comment]
Hi @IrenXu,

Can you answer the following questions so that I can replicate the issue?

1. Which version of TSFEL are you using? 
2. Which operating system are you using? 
3. Can you share your `df`? If possible, just a small version of your dataframe should be enough, or at least a more detailed explanation of the structure of your dataframe.

**Comment by IrenXu** [comment]
Hi,

1. TSFEL version: 0.1.3
2. I'm using Windows
3. The dataset is a 564*5000 matrix and each column is a time point, each row represents an object, and these subjects have different time lengths, so I'm using a loop to filter the nans first and extract features and I aim to get a file containing the features of each time course.

sorry I failed upload my data, npy file is not supported. This figure shows some time courses that have nans. But in my code I have filtered the nans.
![image](https://user-images.githubusercontent.com/77282283/105994214-46462200-609f-11eb-8bd7-1757dd2e780d.png)

**Comment by IrenXu** [comment]
> Hi,
> 
> 1. TSFEL version: 0.1.3
> 2. I'm using Windows
> 3. The dataset is a 564*5000 matrix and each column is a time point, each row represents an object, and these subjects have different time lengths, so I'm using a loop to filter the nans first and extract features and I aim to get a file containing the features of each time course.
> 
> sorry I failed upload my data, npy file is not supported. This figure shows some time courses that have nans. But in my code I have filtered the nans.
> ![image](https://user-images.githubusercontent.com/77282283/105994214-46462200-609f-11eb-8bd7-1757dd2e780d.png)

Sorry, I have solved this....

Thanks so much for your support!

**Comment by mbarandas** [comment]
I will close this issue, but if more issues arise, feel free to contact us.
