### ISSUE TITLE
Regarding ECDF Slope Feature removal

### ISSUE THREAD

**Issue by pyaf** [fraunhoferportugal/tsfel#77]
Hey guys,

Thanks for this awesome library. I saw that in [this commit](https://github.com/fraunhoferportugal/tsfel/commit/ae74f7c2f70b4c939e641295b8a0d03be023e645), ECDF slope feature extraction functionality was removed from the library. It would be great if you guys can explain what was the issue with it.

**Comment by mbarandas** [comment]
Hello,

Thank you for the feedback. ECDF slope was temporarily removed because it was returning NaNs and infinity values. 
We will work to fix this issue in the next release.

**Comment by pyaf** [comment]
Okay, Thanks @mbarandas.
