### ISSUE TITLE
Requirements for input dataframe

### ISSUE THREAD

**Issue by senovr** [fraunhoferportugal/tsfel#79]
Hi, 
I have another question related to the input format of the data for tsfel.

Let's say I have the following dataframe (_time_df_):
```
id  timestamp ch0  ch1 ch2
0   1                0.5   0.8   0.9
0   2                0.9   0.9   0.8
...
0   100              0.8   0.8   0.8
1   1            0.9   0.1   0.1
....
1  50                 0.9   0.9  0.9
2,
3, etc..
```
Where _id_ is the measurement number, and _ch0, ch1, ch2_ are the channels recorded.

Let's say for measurement 0, I had 100 points per channel; for measurement 1, I had 50 points, and for measurement 3, I had 70 points.

Just to put it another way:
 for measurement 0  - an array of 3x100
for measurement 1 - an array of 3x50
for measurement 2- an array of 3x70

The sampling frequency is the same ( let's say 1 sample/second)

When I used tsfresh to generate features, I just providing column with IDs and timestamps
`ts_features = extract_features(time_df, column_id='id', column_sort='timestamp')`
                     

It boils down to the question:
How do I need to re-shape the data frame to use tfsel to generate each measurement's features, regardless of the measurement lengths (they may be the same, or may be different)?

**Comment by dmfolgado** [comment]
Hi!

We didn't considered extracting different window sizes. At the current version, the workaround would be dividing your measurements into different structures, call the feature extraction accordingly and then concatenate the feature results. An example with code in a more readable format is provided below:

```Python
import numpy as np

X = []
for i in range(1, 4):
    X += [extract_features(df.loc[df['id'] == i], column_id="id")]
X = np.vstack(np.array(X))
```

Nevertheless, we might consider implementing such functionality in future releases.

**Comment by senovr** [comment]
Thank you for your comment and explanation, Duarte!

I think it may be valuable to update docs with this use case to avoid repeated questions.
I will close this issue for now.
