### ISSUE TITLE
Sampling Frequency as Integer

### ISSUE THREAD

**Issue by bmaribeiro** [fraunhoferportugal/tsfel#80]
Hello! First of all, thank you for developing this great library.
I've been using it lately, and the dataset I'm working on has a low, non-whole sampling frequency of 1/60 Hz.  Since tsfel assumes the sampling frequency value type as integer, it aproximates that value to zero, which impossibilitates the extraction of some features due to the occurence of "ZeroDivisionError".

**Comment by mbarandas** [comment]
Hi! Thanks for reporting the error. I've just fixed the issue on the development branch. You can install this version by typing "pip install https://github.com/fraunhoferportugal/tsfel/archive/v0.1.5.zip"

**Comment by bmaribeiro** [comment]
Thank you for the quick response! 
I successfully managed to extract all the features, after the update.
