### ISSUE TITLE
Creating/Sampling synthetic time series based on TSFEL extracted features?

### ISSUE THREAD

**Issue by hasanfarooq7** [fraunhoferportugal/tsfel#81]
Hi, I found it to be a great library for time-series features extraction and that too in lightweight manner.
I was wondering if one wants to create/sample synthetic series based on TSFEL extracted features from univariate real series, what should be the way forward and if this going to be a feature in future release? Any suggestions/recommendations in this regard will be highly appreciated.

Many Thanks.

**Comment by dmfolgado** [comment]
Hi! We appreciate your kind feedback. At the moment, we are not considering implementing such functionality. I would say it might not be straightforward, but as a starting point, you will need to define a statistical model with the features of your interest. Afterward, you could use that model to generate samples.

You might want to take a look at [Kang, Y., Hyndman, R. J., & Li, F. (2020). GRATIS: GeneRAting TIme Series with diverse and controllable characteristics. Statistical Analysis and Data Mining: The ASA Data Science Journal, 13(4), 354-376.](https://arxiv.org/pdf/1903.02787.pdf)

It would be quite interesting functionality, though. Let us know if you would proceed with it.

**Comment by hasanfarooq7** [comment]
Sure! Thankyou for pointing to this GRATIS framework. I will update you then. You can close this issue.
