### ISSUE TITLE
Repeated calculation slow down feature calculation

### ISSUE THREAD

**Issue by FreshDPanda** [fraunhoferportugal/tsfel#83]
I apologize in advance if this is not the right place for this post. I am new to Github.
TSFEL repeats basic calculations, such as FFT, for different types of features, which slows down the feature calculation unnecessarily. I work with time series with over 160 million data points and calculating FFT costs 2 minutes each time. Wouldn't it be better to store and retrieve the FFT for the following features?

**Comment by mbarandas** [comment]
Hi. Thanks for the comment.
We are aware of this issue and we are currently working on it. 
In the next release, the computational cost of the feature calculation will be improved.

**Comment by FreshDPanda** [comment]
That's great, I'm looking forward to it. Just to let you know: the calculation of LPCC causes a huge computational overhead on my dataset. This is followed by spectral kurtosis and spectral skewness with the same computation cost.
