### ISSUE TITLE
FFT Frequency Bins (np.linspace vs np.fftfreq) 

### ISSUE THREAD

**Issue by Saniamos** [fraunhoferportugal/tsfel#84]
I've noticed a small inconsistency between the usage of np.fft.fft and the numpy documentation.
Namely in `tsfel/feature_extraction/features_utils.py` in line 52 following (calc_fft).

The numpy documentation at https://numpy.org/doc/stable/reference/generated/numpy.fft.fft.html#numpy.fft.fft
uses fftfreq to extract the center of each frequency bin. While the TSFEL implementation uses np.linspace. 

The output of both functions differs slightly, likely due to accountancy of the zero-frequency component. 
Example:

```
fs = 10
signal_length = 50
a = np.linspace(0, fs // 2, signal_length // 2) # used in calc_fft
b = np.fft.rfftfreq(signal_length, d=1/fs) # numpy documentation
a, b, a.shape, b.shape
```
yields:
```
(array([0.        , 0.20833333, 0.41666667, 0.625     , 0.83333333,
        1.04166667, 1.25      , 1.45833333, 1.66666667, 1.875     ,
        2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667,
        3.125     , 3.33333333, 3.54166667, 3.75      , 3.95833333,
        4.16666667, 4.375     , 4.58333333, 4.79166667, 5.        ]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
        2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ]),
 (25,),
 (26,))
```

The two parts would be equivalent when using `np.linspace(0, fs // 2, signal_length // 2 + 1)`. 

As noted the output differs slightly. If I'm reading this correctly, the linspace is calculated for 25 frequencies including the zero-frequency component, while the rfftfreq is calculated for 25 frequencies plus zero-frequency component.

**Comment by mbarandas** [comment]
Thank you for noticing this issue.

PR #85 was merged on commit e570d0cb898578eac50262168146bd3c5af5d9ef
