### ISSUE TITLE
Not an issue, more of a question about classes

### ISSUE THREAD

**Issue by zygisjas** [fraunhoferportugal/tsfel#87]
How does the dataset should look like in order to create features based on a class of the data. Let's say I have this data, where a class is 1 or 2:

```
      energy.current  energy.power  energy.powerFactor  class  time
0              0.080          12.5                0.67   1     1
1              0.081          12.6                0.67   1     2
2              0.083          12.7                0.66   1     3
3              0.083          12.7                0.66   1     4
4              0.080          12.5                0.67   2     1
5              0.081          12.6                0.67   2     2
6              0.083          12.7                0.66   2     3
7              0.083          12.7                0.66   2     4
```

How do I provide this data to the library for it to be able to generate features by class?

**Comment by dmfolgado** [comment]
Hi! At the moment, we do not support that functionality. However, we have several requests, so we might consider including it in future developments.

As a workaround, you will need to filter your Dataframe by `class`; use `tsfel.time_series_features_extractor` for each class and assign the correspondent class for the features calculated for each window; concatenate all in the end.

Let us know of any further inquiries.

**Comment by dmfolgado** [comment]
I'll close the issue for now. Let us know if you need further assistance!
