### ISSUE TITLE
Feature Reduction

### ISSUE THREAD

**Issue by blindrepository** [fraunhoferportugal/tsfel#89]
Thanks for the useful library.
I would like to use it to extract features from a time-series dataset composed of experiments characterized by 30 synchronous times-series, each collected at 1 Hz. 
By running your code I get 11.700 features. 
Are there any means to automatically reduce the features to the subset your tool evaluate as the most important ones? 

Since I have 400 experiments run a feature selection process afterwards does not seem a good option.

Thanks

**Comment by dmfolgado** [comment]
Hello! Thank your kind words of recognition to our library. At the moment, we do not support any automatic pipeline for feature importance evaluation. You might try using standard preprocessing methods, such as removing correlated features or removing features with low variance. For the first case, you might use [tsfel.correlated_features](https://github.com/fraunhoferportugal/tsfel/blob/master/tsfel/utils/signal_processing.py#L69).

Another experiment you might try is editing the configuration dictionary to reduce the number of features calculated. I will guess that if you disable FFT and Wavelet-related features, the number of calculated features will decrease significantly. You can also try only extracting temporal or statistical features.

```python
cfg = tsfel.get_features_by_domain('statistical')
```

or 

```python
cfg = tsfel.get_features_by_domain('temporal')
```

**Comment by espjose** [comment]
Hola como seria el proceso  para editar el diccionario
