### ISSUE TITLE
Feature extractor doesn't run

### ISSUE THREAD

**Issue by mmarcato** [fraunhoferportugal/tsfel#90]
Hi everyone,

I'm looking to extract features from 3 IMUs each containing a 3-axis Accelerometer and Gyroscopes. I have created a dataframe to combine the data from all of them 3 IMUs x 2 sensors (Acc, Gry) x 3 axis (xyz) = 18 columns + Timestamp

I started out calling the tsfel.get_features_by_domain on the entire dataframe, but that never progressed from 0% Complete. Then, I much reduce the problem: 
- features.json: I copied the original file in the older 'feature_extraction' changed the 'use' from 'yes' to 'no's so it will only calculate [Min, Max, Mean, Median]
- data = selected only one columns and 100 rows with float numbers

`
cfg = tsfel.get_features_by_domain(domain = 'statistical',
                                         json_path = 'features.json')

data = df.loc[s_times[0]:f_times[0], 'Neck.Acc.X'][:101].to_list()

df_tsfel = tsfel.time_series_features_extractor(
        # configuration file with features to be extracted 
        dict_features = cfg,                            
        # dataframe window to calculate features window on 
        signal_windows = data,   
        # sampling frequency of original signal
        fs = 100,
        # sliding window size
        window_size = 100
        )
`

It surely can't get any simpler than this and still it doesn't leave the 0%
![image](https://user-images.githubusercontent.com/54584705/126796948-a36ba619-2d33-4311-aa04-5391d6a22f8c.png)

There must be something wrong with the way I set up stuff. Can someone help please? I'm currentely writting a paper and will need to give up using this package if I dont' manage to sort this out... 

Some extra info:
- Using tsfel==0.1.4
- Windows 10 
- Sample data attached. **
[sample.zip](https://github.com/fraunhoferportugal/tsfel/files/6869581/sample.zip)
**

**Comment by dmfolgado** [comment]
Hello! Thank you for your interest in TSFEL. You're probably not passing the data in the correct input. Please check the right input in the [documentation](https://tsfel.readthedocs.io/en/latest/descriptions/get_started.html). 

I've tested the feature extraction with your data with all available features and ran it in less than one second. Please find below the code I used:

```Python
import tsfel
import pandas as pd

cfg = tsfel.get_features_by_domain()

df = pd.read_csv("sample.csv")
df = df.drop(columns=["Timestamp"])    # You should not pass the timestamp column. Time will be taken into consideration taking into account the length of your input and the sampling frequency.

features = tsfel.time_series_features_extractor(cfg, df, fs=100, window_size=100)
```

Let me know if that helped.

**Comment by mmarcato** [comment]
Hello, thanks so much for getting back to me. 
I tried running exactly the same code and same problem. I'm wondering if this has anything to do with the pandas version I'm using. I recentely hda to update some other code I had because dataframe selection methods have changed, so I needed to update .loc or .iloc.
Find below my requirements.txt for the virtual environment.
[requirements.txt](https://github.com/fraunhoferportugal/tsfel/files/6874752/requirements.txt)

Regards,
Mari

**Comment by mmarcato** [comment]
Hello again Duarte,

I am running exactly the same code you sent me with the exactly same sample.csv file and it doesn't run... 

I'm running this on python 3.8.1. I created a new virtual environment, downloaded your requirements.txt file and installed all the packages from there -  I changed the >= to == to make sure I had the exact same set of packages. 
I have no idea why this is not working... could you share your requirement.txt so I can replicate the exact same environment you are using. 

I'd really appreciate your help in this. 

Regards,
Mari

**Comment by dmfolgado** [comment]
Hello @mmarcato,
I upgraded to the last version of pandas and it is working correctly. My environment packages are available . 
[here](https://github.com/fraunhoferportugal/tsfel/files/6880641/requirements.txt). Can you please provide a print of your `df`variable? I want to make sure it's properly formatted. It should be something like this:

![df](https://user-images.githubusercontent.com/6944301/127046774-3e82fae5-638d-42c7-a10e-3a7c4bf3717a.png)

**Comment by mmarcato** [comment]
Hello @dmfolgado 
Thanks, I will try running it here and will let you know. In the meantime, please find below the df variable. 

![image](https://user-images.githubusercontent.com/54584705/127047679-c87d3483-1cd0-4875-a338-bb8b9b85d97e.png)

I have also tried to convert just one of the columns to a list df['Back.Acc.X'].to_list() to see if that would help, as I noticed in the source code it seems to call a function differently when its a dataframe or list/array. 

I see that you are using a conda environment. I created mine using pip. I'm using VSCode as IDE and using the interactive window there. 

I tried doing some basic debugging to see where the code stops runnin. I can try debugging it properly tomorrow if that could be helpful to you (I wouldn't be the most experienced in that). Here is what I found so far:
- in function time_series_features_extractor 1.variable names is None 2. the code seems to stop running here 
```
  for i, feat in enumerate(features):                    
                    if verbose == 1:
                        display_progress_bar(i, signal_windows, out)
                    features_final = features_final.append(feat)

```
This is the output of the print:
print(feature) = <multiprocessing.pool.IMapIterator object at 0x000002983ADCB670>
print(enumerate(feature)) = <enumerate object at 0x000002983ADD5C80>

Sorry if none of this is useful 😅

**Comment by mmarcato** [comment]
Hello @dmfolgado,
I have a feeling it might be something to do with the progress bar not working in the VSCode interactive window tbh. I spent a long time yesterday trying to make Spyder work with my virtual environment without luck. Then, today I thought of debbugging using VSCode to see where the code stops running, but then it didn't 😂 It worked like magic, same environment, same code, same everything... I thought that changing verbose = 0 would prevent the progress bar from showing, but not really (see image below)

![image](https://user-images.githubusercontent.com/54584705/127146253-d5fcbb53-245a-435f-a9be-72ef70e48c03.png)

I have no idea what is happening really... The joys of coding 😅 At least it works now and I can progress with the feature extraction 🎉Thanks a million for your help, let me know if you have any comments/suggestions 😉😊

**Comment by dmfolgado** [comment]
Hello! I'm glad you solved the issue. We will make more tests on running TSFEL in the integrated consoles from IDEs. Yes, the progress bar shouldn't appear if `verbose=0`. Does it appear if you use the Anaconda IPython and run your script from the terminal?

**Comment by mmarcato** [comment]
It only shows in the IPython Interactive Window only, the terminal doesn't show it. See them in the screenshot 
![image](https://user-images.githubusercontent.com/54584705/127202781-d8c62758-958c-4b4c-9713-69af6b2370da.png)

Adding verbose==1 in the if statement as below seems to fix this issue for me:
` 
        else:
        if isinstance(signal_windows[0], numbers.Real):
            feat_val = calc_window_features(dict_features, signal_windows, fs, verbose=verbose, single_window=True,
                                            features_path=features_path,
                                            header_names=names)
            feat_val.reset_index(drop=True)
            return feat_val
        else:
            # Starting the display of progress bar for notebooks interfaces
            if (get_ipython().__class__.__name__ == 'ZMQInteractiveShell') or (
                    get_ipython().__class__.__name__ == 'Shell'):
            #  I think the if statement above should be replaced by the below
            if verbose == 1 and ((get_ipython().__class__.__name__ == 'ZMQInteractiveShell') or 
              (get_ipython().__class__.__name__ == 'Shell')):

           
                out = display(progress_bar_notebook(0, len(signal_windows)), display_id=True)
            else:
                out = None
`

Also, btw for some reason the interactive window is working fine now 🤷‍♀️ I think that the progress bar never progresses from 0% in the interactive window, but that doesn't mean the function is not calculating features.
