### ISSUE TITLE
Notebook and Google Sheet

### ISSUE THREAD

**Issue by markNZed** [fraunhoferportugal/tsfel#93]
I would ike to get a simple demo of tsfel running so I downloaded the notebooks and run into:

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-14-0cfaaee0f6b7> in <module>
      2 googleSheet_name = "MH Copy of Features_dev"
      3 # Extract excel info
----> 4 cfg_file = tsfel.extract_sheet(googleSheet_name)
      5 
      6 # Get features

~/Library/Python/3.6/lib/python/site-packages/tsfel/utils/gSheetsFilters.py in extract_sheet(gsheet_name, **kwargs)
    111 
    112     assert len(list_of_features) <= (len_json), \
--> 113         "To insert a new feature, please add it to data/features.json with the code in src/utils/features.py"
    114 
    115     # adds a new feature in Google sheet if it is missing from features.json

AssertionError: To insert a new feature, please add it to data/features.json with the code in src/utils/features.py

```

I'm not sure the first demo should use Google sheets - maybe that table could be inserted into the Notebook?

**Comment by dmfolgado** [comment]
We corrected the Google Sheets feature configuration file. You should no longer encounter any issues. The additional demos we provide do not rely on Google Sheets. In the development branch, the ./notebooks folder now has an additional example notebook that will be transferred to the master branch in the upcoming release.

As a final note, we're currently in the process of replacing the Google Sheets with an alternative method for scenarios where the user would prefer a GUI to configure which features will be extracted.
