### ISSUE TITLE
Low sample rate

### ISSUE THREAD

**Issue by markNZed** [fraunhoferportugal/tsfel#95]
I have a series with a sample frequency of 5minutes, so sample rate 0.0033 
`	X_train = tsfel.time_series_features_extractor(cfg_file, X_train_sig, fs=0.0033, window_size=12)`

but I get an error:

```
Name: value, dtype: float64
*** Feature extraction started ***
/Users/markh/Library/Python/3.6/lib/python/site-packages/scipy/signal/spectral.py:1800: RuntimeWarning: divide by zero encountered in double_scalars
  scale = 1.0 / (fs * (win*win).sum())

```
Must the sample rate be > 1 ?

**Comment by mbarandas** [comment]
Hi! Thanks for reporting the error. This bug was already fixed on the development branch. You can install this version by typing "pip install https://github.com/fraunhoferportugal/tsfel/archive/v0.1.5.zip"
