### ISSUE TITLE
Minimal sample window size

### ISSUE THREAD

**Issue by markNZed** [fraunhoferportugal/tsfel#97]
I'm using:
```
X_train = tsfel.time_series_features_extractor(cfg_file, X_train_sig, fs=fs, window_size=window_size)
```
There is a minimal sample window size of 12?

If I use a smaller window_size then I get errors like below (I'm running through Julia so the messages are not so nice)

```File "..../tsfel/feature_extraction/calc_features.py", line 297, in time_series_features_extractor for i, feat in enumerate(features):```

**Comment by mbarandas** [comment]
Hi! There is no minimal window size. 

What is causing the error is the lpcc feature that by default tries to extract 12 coefficients. You can remove lpcc feature from your configuration file or change the number of coefficients.

We will try to handle this issue in the next TSFEL release.

**Comment by Sourajit2110** [comment]
I guess minimal sample window size is not the reason if you're getting "**SystemExit: Empty signal windows. Please check window size input parameter.**" error. To resolve this error, you may need to check if the input data is valid or not accessed out of bound index.

**Comment by Shaswati** [comment]
I guess minimal sample window size is not the reason if you're getting "SystemExit: Empty signal windows. Please check window size input parameter." error. To resolve this error, you may need to check if the input data is valid or not accessed out of bound index.
